import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { DM_Sans, Red_Hat_Display, Noto_Sans_HK, } from "next/font/google";
import ScrollbarWatcher from "@/components/ScrollbarWatcher";
// Define the font
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-red-hat-display",
  display: "swap",
});
const NotoSansHK = Noto_Sans_HK({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans-hk",
  display: "swap",
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dmSans.variable} ${redHatDisplay.variable} ${NotoSansHK.variable}`}>
      <body className="font-dm-sans">
        <ScrollbarWatcher />
        {children}
      </body>
    </html>
  );
}
