import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans, Red_Hat_Display, Noto_Sans_HK } from "next/font/google";

import ScrollbarWatcher from "@/components/ScrollbarWatcher";
import "./globals.css";

// Font Definitions
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dm-sans",
  display: "swap",
});

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-red-hat-display",
  display: "swap",
});

const notoSansHK = Noto_Sans_HK({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans-hk",
  display: "swap",
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${redHatDisplay.variable} ${notoSansHK.variable} ${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="font-dm-sans" suppressHydrationWarning>
        <ScrollbarWatcher />
        {children}
      </body>
    </html>
  );
}
